import { idDictionary } from "@/helpers/constants/id-dictionary"
import { pageSummaryStyle } from "@/helpers/constants/page-summary-style"

export function setupSummaryOverlay(summary: string) {
    document.getElementById(idDictionary.pageSummaryOverlay)?.remove()
    
    const overlay = document.createElement('div')
    overlay.id = idDictionary.pageSummaryOverlay

    const shadow = overlay.attachShadow({ mode: 'open' })

    shadow.innerHTML = `
    ${pageSummaryStyle}
    <div class="summary-panel-backdrop" id=${idDictionary.pageSummaryOverlayBackdrop}></div>
    <div class="summary-panel">
        <button id=${idDictionary.pageSummaryOverlayButton}>Close</button>
        <div class="summary-panel-content">${summary}</div>
        <p><b>Page summaries are generated by AI, and may be inaccurate. Please verify that important information is correct.</b></p>
    </div>
    `

    const closeOverlay = () => overlay.remove()

    shadow.getElementById(idDictionary.pageSummaryOverlayButton)!.addEventListener('click', closeOverlay)
    shadow.getElementById(idDictionary.pageSummaryOverlayBackdrop)!.addEventListener('click', closeOverlay)

    document.body.appendChild(overlay)
}